version: 1.0.{build}
image: Visual Studio 2019
clone_folder: c:\projects\asa
init:
- cmd: >-
    set

    set PATH=C:\Qt\%qt%\bin;%PATH%

    set QTDIR=C:\Qt\%qt%

    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat" -arch=x86
environment:
  matrix:
  - qt: 5.15.2\msvc2019
    build_arch: win32
install:
- cmd: >-
    cd ../

    git clone https://github.com/polovik/3rd-party.git

    cd 3rd-party/libtiff

    qmake -spec win32-msvc -tp vc libtiff.pro

    msbuild tiff.vcxproj /p:Configuration=Release

    cd ../../asa/
build_script:
- cmd: >-
    qmake -spec win32-msvc -tp vc analog_signature_analyzer.pro

    msbuild asa.vcxproj /p:Configuration=Release

    windeployqt --no-translations ..\build

    set buildname=asa-%APPVEYOR_BUILD_VERSION%_%APPVEYOR_REPO_COMMIT:~0,7%

    7z a -tzip %buildname%_%build_arch%.zip ..\build\*
artifacts:
- path: '*.zip'
on_image_bake:
- cmd: ''