version: 1.0.0.{build}
environment:
  matrix:
  # MinGW
  - name: win32
    platform: mingw
    qt: 5.6\mingw49_32
    suffix: mingw

init:
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=C:\Qt\Tools\mingw492_32\bin;%PATH%
  - set PATH=C:\Qt\%qt%\bin;%PATH%
  - set QTDIR=C:\Qt\%qt%
  - set makefiles="MinGW Makefiles"
  - if %APPVEYOR_REPO_TAG%==true (set nogitinfo=ON) else (set nogitinfo=OFF)

install:
  - cd ../
  - git clone https://github.com/polovik/3rd-party.git
  - cd 3rd-party/libtiff
  - qmake libtiff.pro
  - mingw32-make -j 4
  - cd ../../asa/

build_script:
  - qmake analog_signature_analyzer.pro
  - mingw32-make -j 4

after_build:
  - set buildname=asa-%APPVEYOR_BUILD_VERSION%_%APPVEYOR_REPO_COMMIT:~0,7%
  - 7z a -tzip %buildname%_%name%.zip ..\build\*

artifacts:
  - path: '*.zip'
