version: 1.0.0.{build}
environment:
  matrix:
  # MinGW
  - name: win32
    platform: mingw
    qt: 5.6\mingw49_32
    suffix: mingw

init:
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=C:\Qt\Tools\mingw492_32\bin;%PATH%
  - set PATH=C:\Qt\%qt%\bin;%PATH%
  - set makefiles="MinGW Makefiles"
  - if %APPVEYOR_REPO_TAG%==true (set nogitinfo=ON) else (set nogitinfo=OFF)

install:
  - git clone https://github.com/polovik/3rd-party.git
  - cd 3rd-party/libtiff
  - qmake libtiff.pro
  - mingw32-make -j 4

build_script:
  - qmake analog_signature_analyzer.pro
  - mingw32-make -j 4

